export const demoComponentManifests = [
  {
    id: 'article',
    exportName: 'articleCard',
    name: '文章摘要卡',
    dir: 'article-card',
    data: {
      eyebrow: 'GENERATE SHARING',
      title: '用 WXML/WXSS 生成分享卡片',
      body: '这个 demo 在小程序中读取真实组件目录，通过 API 转成模板字符串，再由 DSL 渲染到 Canvas。',
      author: 'Codex',
      date: '2026.07',
    },
  },
  {
    id: 'profile',
    exportName: 'profileCard',
    name: '头像资料卡',
    dir: 'profile-card',
    data: {
      avatar: '/assets/avatar.svg',
      name: 'Tempest',
      role: '小程序模板作者',
      summary: '真实组件可以先在构建期读取 index.wxml 和 index.wxss，再交给小程序端 runtime 绘制。',
      badge: 'PRO',
    },
  },
  {
    id: 'composite',
    exportName: 'compositeCard',
    name: '嵌套组件卡',
    dir: 'composite-card',
    data: {
      title: '组件组合能力',
      summary: '父组件通过 usingComponents 引用统计子组件，构建时递归展开后交给 Canvas DSL。',
      firstLabel: '模板节点',
      firstValue: '18',
      secondLabel: '渲染指令',
      secondValue: '42',
    },
  },
  {
    id: 'metrics',
    exportName: 'metricsCard',
    name: '数据指标卡',
    dir: 'metrics-card',
    data: {
      kicker: 'DASHBOARD',
      title: '关键指标一屏展示',
      primaryLabel: '生成模板',
      primaryValue: '7',
      secondLabel: '图片资源',
      secondValue: '2',
      thirdLabel: '组件层级',
      thirdValue: '3',
      note: '用于验证纵向信息密度、重复模块和文本行高。',
    },
  },
  {
    id: 'deep-nested',
    exportName: 'deepNestedCard',
    name: '多层嵌套组件卡',
    dir: 'deep-nested-card',
    data: {
      title: '父组件 -> 区块组件 -> 信息行',
      description: '这个 demo 包含两层 usingComponents，用于验证构建工具递归展开本地自定义组件。',
      sectionTitle: '展开结果',
      firstLabel: '父组件',
      firstValue: 'deep-card',
      secondLabel: '子组件',
      secondValue: 'info-row',
      footer: '所有自定义标签会在构建期展开为 view/text。',
    },
  },
  {
    id: 'product',
    exportName: 'productCard',
    name: '图片商品卡',
    dir: 'product-card',
    data: {
      cover: '/assets/cover.svg',
      label: 'NEW TEMPLATE',
      title: '复杂图片分享卡',
      description: '包含封面图、标签、标题、说明和价格信息，适合验证 image、嵌套 view 和横向布局。',
      price: '¥ 128',
      note: 'Canvas DSL Demo',
    },
  },
];
